---
- hosts: local
  vars:
  tasks:
  # - name: GET repo
  #   uri:
  #     url: http://localhost:8081/service/rest/v1/repositories
  - name: Create a JIRA issue
    uri:
      url: http://localhost:8081/service/rest/v1/repositories/apt/hosted
      method: POST
      user: admin
      password: admin123
      headers:
        Content-Type: application/json
        Accept: application/json
      body: 
        mainlevel:
          subkey: finalvalue
        name: external
        online: true
        storage: 
          blobStoreName: default
          strictContentTypeValidation: true,
          writePolicy: allow_once
        cleanup:
          policyNames: 
            - string
        component:
          proprietaryComponents: true
        apt:
          distribution: bionic
        aptSigning:
          keypair: string
          passphrase: string
      force_basic_auth: yes
      status_code: 201
      body_format: json