---
- hosts: local
  vars:
    aptrepos:
    - url: http://localhost:8081/service/rest/v1/repositories/apt/hosted
      name: external
      id: external
    - url: http://localhost:8081/service/rest/v1/repositories/apt/hosted
      name: internal
      id: internal
  tasks:
  - name: Create a nexus apt repo
    uri:
      url: {{ item.url }}
      method: POST
      user: admin
      password: admin123
      headers:
        Content-Type: application/json
        Accept: application/json
      body: 
        mainlevel:
          subkey: finalvalue
        name: "{{ item.name }}"
        online: true
        storage: 
          blobStoreName: default
          strictContentTypeValidation: true,
          writePolicy: allow_once
        cleanup:
          policyNames: 
            - string
        component:
          proprietaryComponents: true
        apt:
          distribution: bionic
        aptSigning:
          keypair: string
          passphrase: string
      force_basic_auth: yes
      status_code: 201
      body_format: json
    with_items: "{{ aptrepos }}"
