---
- hosts: local
  vars:
    HtpasswdsToSet:
    - path: /etc/nginx/passwdfile
      name: janedoe
      password: 'abc123'
    - path: /etc/nginx/passwdfile
      name: bob
      password: '123abc'
  tasks:
  - name: add htpasswd users
    debug:
      msg: "{{item.path}}-{{item.name}}-{{item.password}}"
    with_items: "{{HtpasswdsToSet}}"
  