---
- name: get nexus docker repos
  uri:
    url: "{{ item.url }}/{{ item.name }}"
    method: GET
    user: admin
    password: admin123
    headers:
        Accept: application/json
    force_basic_auth: "yes"
    body_format: json
  register: repo_output
  ignore_errors: "yes"
- debug:
    msg: "{{ '{\"status\": \"SUCCESS\"}' if (repo_output['json'] == 'Repository not found') else '{\"status\" : \"FAILED\"}' }}"
- name: Set facts for delete operation results
  set_fact:
    repo_get_result: "{{ '{\"status\": \"SUCCESS\"}' if (repo_output['json'] == 'Repository not found') else '{\"status\" : \"FAILED\"}' }}"
- name: create nexus repo
  debug:
    msg: "creating the repo"
  when: repo_get_result.status == "SUCCESS"
- name: create a template
  template:
    src: apt.json.j2
    dest: /tmp/apt.json
- name: Create a nexus repo
    uri:
      url: http://localhost:8081/service/rest/v1/repositories/apt/hosted
      method: POST
      user: admin
      password: admin123
      headers:
        Content-Type: application/json
        Accept: application/json
      body: "{{ lookup('file','/tmp/apt.json') }}"
      force_basic_auth: yes
      status_code: 201
      body_format: json
    when: repo_get_result.status == "SUCCESS"