---
- name: Create a nexus apt repo
  uri:
    url: "{{ item.url }}"
    method: POST
    user: admin
    password: admin123
    headers:
        Content-Type: application/json
        Accept: application/json
    body: 
        mainlevel:
            subkey: finalvalue
        name: "{{ item.name }}"
        online: "true"
        storage: 
            blobStoreName: default
            strictContentTypeValidation: "true"
            writePolicy: allow_once
        cleanup:
            policyNames: 
            - string
        component:
            proprietaryComponents: "true"
        apt:
            distribution: bionic
        aptSigning:
            keypair: string
            passphrase: string
    force_basic_auth: "yes"
    status_code: 201
    body_format: json
  with_items: "{{ aptrepos }}"
  ignore_errors: "yes"
- name: Create a nexus maven repo
  uri:
    url: "{{ item.url }}"
    method: POST
    user: admin
    password: admin123
    headers:
        Content-Type: application/json
        Accept: application/json
    body: 
        name: "{{ item.name }}"
        online: "true"
        storage:
            blobStoreName: default
            strictContentTypeValidation: "true"
            writePolicy: allow_once
        cleanup:
            policyNames:
            - string
        component:
            proprietaryComponents: "true"
        maven:
            versionPolicy: MIXED
            layoutPolicy: STRICT
            contentDisposition: ATTACHMENT
    force_basic_auth: "yes"
    status_code: 201
    body_format: json
  with_items: "{{ mavenrepos }}"
  ignore_errors: "yes"
- name: get nexus docker repos
  uri:
    url: "{{ item.url }}/{{ item.name }}"
    method: GET
    user: admin
    password: admin123
    headers:
        Accept: application/json
    force_basic_auth: "yes"
    body_format: json
  with_items: "{{ dockerrepos }}"
  register: docker_output
- debug:
    msg: "{{ docker_output.results[0].item.name }}"
- debug:
    msg: "{{ docker_output.results[1].item.name }}"
# - name: Create a nexus docker repo
#   uri:
#     url: "{{ item.url }}"
#     method: POST
#     user: admin
#     password: admin123
#     headers:
#         Content-Type: application/json
#         Accept: application/json
#     body: 
#         name: "{{ item.name }}"
#         online: "true"
#         storage:
#             blobStoreName: default
#             strictContentTypeValidation: "true"
#             writePolicy: allow_once
#         cleanup:
#             policyNames:
#             - string
#         component:
#             proprietaryComponents: "true"
#         docker:
#             v1Enabled: "false"
#             forceBasicAuth: "true"
#             # httpPort: 8082
#             # httpsPort: 8083
#     force_basic_auth: "yes"
#     status_code: 201
#     body_format: json
#   with_items: "{{ dockerrepos }}"
#   ignore_errors: "yes"
    
   
